repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system  # Usar o pylint do sistema
        types: [python]
        args:
          - "--disable=R,C"  # Desativa categorias de mensagens específicas
          - "--rcfile=.pylintrc"  # Corrigido: arquivo de configuração do pylint
          - "--load-plugins=pylint.extensions.docparams"  # Carrega o plugin docparams